### ISSUE TITLE
`OrderedCollections` module fails to build with Bazel

### ISSUE THREAD

**Issue by chizcake** [apple/swift-collections#136] opened 2021-12-22 02:05 UTC
### Information

- **Package version:** 1.0.0
- **Platform version:** macOS 12.1 (21C52)
- **Swift version:** Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing GitHub issues](https://github.com/apple/swift-collections/issues).

### Steps to Reproduce
I'm using [Bazel](https://github.com/bazelbuild/rules_swift) build system and I met a build failure with the following stack trace whenever I tried to use xcconfig which had `-assert-config Debug` flag:

```
INFO: From Compiling Swift module OrderedCollections:
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project and the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode-13.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c external/Collections/Sources/OrderedCollections/HashTable/_HashTable+Bucket.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable+BucketIterator.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable+Constants.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable+CustomStringConvertible.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable+Testing.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift external/Collections/Sources/OrderedCollections/HashTable/_HashTable.swift external/Collections/Sources/OrderedCollections/HashTable/_Hashtable+Header.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Codable.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomDebugStringConvertible.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomReflectable.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomStringConvertible.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Deprecations.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Equatable.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+ExpressibleByDictionaryLiteral.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Hashable.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Invariants.swift "external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial MutableCollection.swift" "external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial RangeReplaceableCollection.swift" external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sequence.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift external/Collections/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Codable.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomDebugStringConvertible.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomReflectable.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomStringConvertible.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Diffing.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Equatable.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+ExpressibleByArrayLiteral.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Hashable.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Invariants.swift "external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial MutableCollection.swift" "external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial RangeReplaceableCollection.swift" "external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Basics.swift" "external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Operations.swift" "external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Predicates.swift" external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+RandomAccessCollection.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+ReserveCapacity.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+Testing.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet+UnstableInternals.swift external/Collections/Sources/OrderedCollections/OrderedSet/OrderedSet.swift external/Collections/Sources/OrderedCollections/Utilities/RandomAccessCollection+Offsets.swift external/Collections/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift -supplementary-output-file-map /var/folders/4n/33t8hhln04s0cvfg31h8kqpm0000gp/T/TemporaryDirectory.Lj9WJD/supplementaryOutputs-1 -target arm64-apple-ios13.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -I /Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -I /__build_bazel_rules_swift/swiftmodules -F /Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F /Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/Developer/Library/Frameworks -assert-config Debug -g -module-cache-path /var/folders/4n/33t8hhln04s0cvfg31h8kqpm0000gp/T/swift_module_cache.cLDFaN -swift-version 5 -Osize -D NDEBUG -D BAZEL -debug-prefix-map /private/var/tmp/_bazel_KJKIM/9dbf82519b813fdab4f1790d456d1805/execroot/line_ios=. -debug-prefix-map /Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/include/objc/.=/Applications/Xcode-13.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/include/objc -new-driver-path /Applications/Xcode-13.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -no-clang-module-breadcrumbs -no-serialize-debugging-options -vfsoverlaybazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections.vfsoverlay.yaml -color-diagnostics -resource-dir /Applications/Xcode-13.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -Xcc -iquote. -Xcc -iquotebazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin -Xcc -Ibazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_private_hmap.hmap -Xcc -Ibazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_public_hmap.hmap -Xcc -Ibazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_private_angled_hmap.hmap -Xcc -I. -Xcc -iquote -Xcc bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_private_hmap.hmap -Xcc -Oz -Xcc -fno-unroll-loops -Xcc -fno-jump-tables -Xcc -Os -Xcc -DNDEBUG=1 -Xcc -Wno-unused-variable -Xcc -Winit-self -Xcc -Wno-extra -module-name OrderedCollections -target-sdk-version 15.2.0 -parse-as-library -num-threads 12 -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+Bucket.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+BucketIterator.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+Constants.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+CustomStringConvertible.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+Testing.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_HashTable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/HashTable/_Hashtable+Header.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Codable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomDebugStringConvertible.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomReflectable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+CustomStringConvertible.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Deprecations.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Equatable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+ExpressibleByDictionaryLiteral.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Hashable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Invariants.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial__SPACE__MutableCollection.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial__SPACE__RangeReplaceableCollection.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sequence.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Codable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomDebugStringConvertible.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomReflectable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+CustomStringConvertible.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Diffing.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Equatable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+ExpressibleByArrayLiteral.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Hashable.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Invariants.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial__SPACE__MutableCollection.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial__SPACE__RangeReplaceableCollection.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial__SPACE__SetAlgebra+Basics.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial__SPACE__SetAlgebra+Operations.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Partial__SPACE__SetAlgebra+Predicates.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+RandomAccessCollection.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+ReserveCapacity.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+Testing.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet+UnstableInternals.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/OrderedSet/OrderedSet.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/Utilities/RandomAccessCollection+Offsets.swift.o -o bazel-out/ios-arm64-min13.0-applebin_ios-ios_arm64-opt-ST-dddd6af9e792/bin/external/Collections/OrderedCollections_objs/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift.o
1.	Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
2.	
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, Serialize, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for OrderedCollections.OrderedCollections)
4.	While running pass #382999 SILFunctionTransform "LICM" on SILFunction "@$ss30_copySequenceToContiguousArrayys0dE0Vy7ElementQzGxSTRzlF18OrderedCollections13_UnsafeBitsetV_Tgq5".
 for <<debugloc at "<compiler-generated>":0:0>>Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000114effc27 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 39
1  swift-frontend           0x0000000114efebb8 llvm::sys::RunSignalHandlers() + 248
2  swift-frontend           0x0000000114f00236 SignalHandler(int) + 278
3  libsystem_platform.dylib 0x00007fff20591d7d _sigtramp + 29
4  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603339973452448
5  swift-frontend           0x0000000110970f7c (anonymous namespace)::LICM::run() + 1020
6  swift-frontend           0x0000000110a37179 swift::SILPassManager::runFunctionPasses(unsigned int, unsigned int) + 4409
7  swift-frontend           0x0000000110a332eb swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 155
8  swift-frontend           0x0000000110a4dbcc swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 60
9  swift-frontend           0x0000000110a3b9c5 llvm::Expected<swift::ExecuteSILPipelineRequest::OutputType> swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest>(swift::ExecuteSILPipelineRequest const&) + 469
10 swift-frontend           0x0000000110a3e108 swift::runSILOptimizationPasses(swift::SILModule&) + 392
11 swift-frontend           0x0000000110185004 swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 1108
12 swift-frontend           0x000000011001c143 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1187
13 swift-frontend           0x000000011000e6d7 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 14743
14 swift-frontend           0x000000010ff4eb08 main + 1032
15 libdyld.dylib            0x00007fff20567f5d start + 1
16 libdyld.dylib            0x00000000000000ea start + 18446603339973624206
```

Surprisingly, `swiftc` frontend does not complain if I don't use `-assert-config Debug` flag. It seems like there's something wrong with [_UsafeBitset.Word.next()](https://github.com/apple/swift-collections/blob/22dc81b89fc1dee9d52c6a3fcfa1fcd08f184ae8/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift#L378-L385) and I tweaked it a little so that I could make it built even with `-assert-config Debug` flag:

```diff
diff --git a/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift b/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift
index 9470c61..56d41a5 100644
--- a/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift
+++ b/Sources/OrderedCollections/Utilities/_UnsafeBitset.swift
@@ -268,12 +268,18 @@ extension _UnsafeBitset {
   @frozen
   internal struct Word {
     @usableFromInline
-    internal var value: UInt
+    internal var value: UInt {
+      didSet { _value = value }
+    }
+
+    @usableFromInline
+    internal var _value: UInt
 
     @inlinable
     @inline(__always)
     internal init(_ value: UInt) {
       self.value = value
+      self._value = value
     }
   }
 }
@@ -378,7 +384,7 @@ extension _UnsafeBitset.Word: Sequence, IteratorProtocol {
   @inlinable
   internal mutating func next() -> Int? {
     guard value != 0 else { return nil }
-    let bit = value.trailingZeroBitCount
+    let bit = _value.trailingZeroBitCount
     value &= value &- 1       // Clear lowest nonzero bit.
     return bit
   }
```

I don't know why my tweak works though.. 🤔 

### Expected behavior
`OrderedCollections` module could be built.

### Actual behavior
`OrderedCollections` module could not be built.

**Comment by lorentey** [comment] 2021-12-27 08:08
Bazel is not a supported build system for this package. 

That said, this is very likely a real issue in the compiler, and it would be useful if we could diagnose it! 

So far I haven't seen this compiler crash triggering with our supported build systems (SPM, Xcode's Swift package support and CMake), so I expect this is something specific to how Bazel invokes swiftc. Can you please provide detailed reproduction steps? (Preferably a failing compiler invocation that we can run on a freshly cloned copy of this repo, or at the very least, the full details on how you build this code with Bazel.)

**Comment by chizcake** [comment] 2022-01-03 07:34
@lorentey Thanks for the feedback! I'll add another comment after I could make a reproducible sample with Bazel.

**Comment by lorentey** [comment] 2022-09-19 23:11
Closing due to current lack of actionable work. Please reopen with a reproducer if this continues to be a problem.

**Closed by lorentey** 2022-09-19 23:11 UTC
Labels: bug
